-- CAR
INSERT INTO CAR (ID, FREE_SEATS) VALUES (1, '3');

-- HOME ADDRESS
INSERT INTO ADDRESS (ID, ADDRESS, LATITUDE, LONGITUDE, TYPE)
VALUES (1, 'Home Street, 1, SPB, RU', 60.0145399, 30.2595844, 'HOME');

-- OFFICE ADDRESS
INSERT INTO ADDRESS (ID, ADDRESS, LATITUDE, LONGITUDE, TYPE)
VALUES (2, 'Work Street, 1, SPB, RU', 30.2595844, 60.0145399, 'OFFICE');

-- USER
INSERT INTO USER (
  ACTIVE, CREATED, DRIVER, EMAIL, IN_OFFICE_HOUR, FROM_OFFICE_HOUR, NAME, PASSWORD, PHONE, ROLE, CAR_ID, HOME_ADDRESS_ID, OFFICE_ADDRESS_ID)
VALUES (TRUE, now(), TRUE, 'abc@abc.com', 10, 19, 'John Smith',
              'P@ssw0rd', '+7 999 1234567', 'USER', 1, 1, 2);